### ISSUE TITLE
Stops_ft should be optional

### ISSUE THREAD

**Issue by e-lo** [MetropolitanTransportationCommission/fast-trips#55]
Per https://github.com/osplanning-data-standards/GTFS-PLUS

but when not included, get an error:

```
Traceback (most recent call last):
  File "scripts/runTest.py", line 108, in <module>
    ft.read_input_files()
  File "/Users/elizabeth/Documents/urbanlabs/MTC/SHRP2/working/fast-trips/fasttrips/FastTrips.py", line 122, in read_input_files
    self.gtfs_schedule)
  File "/Users/elizabeth/Documents/urbanlabs/MTC/SHRP2/working/fast-trips/fasttrips/Stop.py", line 95, in __init__
    dtype={Stop.STOPS_COLUMN_STOP_ID:object})
  File "//anaconda/envs/Fast-Trips/lib/python2.7/site-packages/pandas/io/parsers.py", line 646, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "//anaconda/envs/Fast-Trips/lib/python2.7/site-packages/pandas/io/parsers.py", line 389, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "//anaconda/envs/Fast-Trips/lib/python2.7/site-packages/pandas/io/parsers.py", line 730, in __init__
    self._make_engine(self.engine)
  File "//anaconda/envs/Fast-Trips/lib/python2.7/site-packages/pandas/io/parsers.py", line 923, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "//anaconda/envs/Fast-Trips/lib/python2.7/site-packages/pandas/io/parsers.py", line 1390, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 373, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4184)
  File "pandas/parser.pyx", line 667, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:8449)
IOError: File Examples/tta/input/network-simple/stops_ft.txt does not exist
2017-04-25 10:37:27 [INFO/MainProcess] process shutting down
```

**Comment by e-lo** [comment]
This worked when tested, so closing.
