### ISSUE TITLE
From_route_id should be optional in transfers_ft.txt

### ISSUE THREAD

**Issue by e-lo** [MetropolitanTransportationCommission/fast-trips#56]
Per: https://github.com/osplanning-data-standards/GTFS-PLUS/blob/master/files/transfers_ft.md

But...

```
Traceback (most recent call last):
  File "scripts/runTest.py", line 108, in <module>
    ft.read_input_files()
  File "/Users/elizabeth/Documents/urbanlabs/MTC/SHRP2/working/fast-trips/fasttrips/FastTrips.py", line 130, in read_input_files
    self.gtfs_schedule)
  File "/Users/elizabeth/Documents/urbanlabs/MTC/SHRP2/working/fast-trips/fasttrips/Transfer.py", line 162, in __init__
    one_route_specified_df = self.transfers_df.loc[ self.transfers_df[Transfer.TRANSFERS_COLUMN_FROM_ROUTE].notnull()^
  File "//anaconda/envs/Fast-Trips/lib/python2.7/site-packages/pandas/core/frame.py", line 2059, in __getitem__
    return self._getitem_column(key)
  File "//anaconda/envs/Fast-Trips/lib/python2.7/site-packages/pandas/core/frame.py", line 2066, in _getitem_column
    return self._get_item_cache(key)
  File "//anaconda/envs/Fast-Trips/lib/python2.7/site-packages/pandas/core/generic.py", line 1386, in _get_item_cache
    values = self._data.get(item)
  File "//anaconda/envs/Fast-Trips/lib/python2.7/site-packages/pandas/core/internals.py", line 3543, in get
    loc = self.items.get_loc(item)
  File "//anaconda/envs/Fast-Trips/lib/python2.7/site-packages/pandas/indexes/base.py", line 2136, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13742)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)
KeyError: 'from_route_id'
```

**Comment by e-lo** [comment]
[ and i'm assuming that this is also issue with other optional attributes, so should go down the list ]

**Comment by e-lo** [comment]
etc...stop_times_ft

```
Traceback (most recent call last):
  File "scripts/runTest.py", line 108, in <module>
    ft.read_input_files()
  File "/Users/elizabeth/Documents/urbanlabs/MTC/SHRP2/working/fast-trips/fasttrips/FastTrips.py", line 135, in read_input_files
    self.stops, self.routes, Assignment.PREPEND_ROUTE_ID_TO_TRIP_ID)
  File "/Users/elizabeth/Documents/urbanlabs/MTC/SHRP2/working/fast-trips/fasttrips/Trip.py", line 379, in __init__
    Trip.STOPTIMES_COLUMN_STOP_ID:object})
  File "//anaconda/envs/Fast-Trips/lib/python2.7/site-packages/pandas/io/parsers.py", line 646, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "//anaconda/envs/Fast-Trips/lib/python2.7/site-packages/pandas/io/parsers.py", line 389, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "//anaconda/envs/Fast-Trips/lib/python2.7/site-packages/pandas/io/parsers.py", line 730, in __init__
    self._make_engine(self.engine)
  File "//anaconda/envs/Fast-Trips/lib/python2.7/site-packages/pandas/io/parsers.py", line 923, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "//anaconda/envs/Fast-Trips/lib/python2.7/site-packages/pandas/io/parsers.py", line 1390, in __init__
    self._reader = _parser.TextReader(src, **kwds)
  File "pandas/parser.pyx", line 373, in pandas.parser.TextReader.__cinit__ (pandas/parser.c:4184)
  File "pandas/parser.pyx", line 667, in pandas.parser.TextReader._setup_parser_source (pandas/parser.c:8449)
IOError: File Examples/tta/input/network-simple/stop_times_ft.txt does not exist
```

**Comment by e-lo** [comment]
This worked when I tested it, so closing.
