### ISSUE TITLE
Put package on PyPi

### ISSUE THREAD

**Issue by e-lo** [MetropolitanTransportationCommission/fast-trips#59]
It will be easier for tutorial. I've never done this before, but there appear to be [directions here](https://packaging.python.org/distributing/)

**Comment by e-lo** [comment]
@lmz : are we here yet? :)

**Comment by lmz** [comment]
Working on it: https://pypi.python.org/pypi/fasttrips

**Comment by lmz** [comment]
But I don't have my mac with me so I can't compile a mac version until I go get it

**Comment by e-lo** [comment]
:-D  and os-x?

**Comment by lmz** [comment]
If you want to register on pypi I can make you an owner too

**Comment by lmz** [comment]
I can also just go get my mac and do it this afternoon :octocat:

**Comment by e-lo** [comment]
Merge to master?

**Comment by lmz** [comment]
I haven't been able to install the package yet so there's still something wrong...

**Comment by e-lo** [comment]
gotcha

**Comment by e-lo** [comment]
Also make sure the tests pass...

**Comment by e-lo** [comment]
LMK if I can help with this one - I think it is the last thing remaining ahead of posting the tutorial and install directions more publicly.

**Comment by lmz** [comment]
I think I got it in the next few min

**Comment by lmz** [comment]
Ok, I have a version up for mac and windows:
https://pypi.python.org/pypi/fasttrips
I don't know if the files are in the right place but I know they're in there.  :face_with_thermometer:

**Comment by e-lo** [comment]
I tried to install using pip install and pip said it completed just fine [ and also installed transitfeed for me ]...but then the only folders that showed up in site-packages was `/Examples/test_network` and `/tests` - I wonder if it only packaged the tests for some reason?

<img width="422" alt="screen shot 2017-05-09 at 10 43 24 am" src="https://cloud.githubusercontent.com/assets/794787/25864514/8c805c3e-34a4-11e7-987f-e03f8596a47b.png">

`import fasttrips` obviously also fails

**Comment by lmz** [comment]
Ok, try it now?  I think alpha 7 works on both.  Also try `run_fasttrips` at the command line.

**Comment by e-lo** [comment]
Ok - it installs the package [ yay ] but it doesn't install scripts, non-test items, and the relative paths are now kinda screwy.
<img width="838" alt="screen shot 2017-05-09 at 3 05 12 pm" src="https://cloud.githubusercontent.com/assets/794787/25874792/173b49fa-34c9-11e7-9ded-74a384e19a93.png">

**Comment by e-lo** [comment]
I mean - this should actually be ok for the tutorial since it uses separate data and scripts...

**Comment by lmz** [comment]
where should we put data? Right now it's putting it in the default location which is in the site-packages/fasttrips.  Not sure what would be better or if there's a better way to point users to it.

**Comment by e-lo** [comment]
I guess it is fine there?  although unfortunately I get this error:
```

(//anaconda/envs/ft-tutorial-testing) bash-3.2$ run_fasttrips stochastic 1 Examples/test_scenario/demand_reg/config_ft.txt Examples/test_scenario/network Examples/test_scenario/demand_reg Examples/test_scenario/demand_reg/pathweight_ft.txt Examples/test_scenario/output_demand_reg
{'transfer_fare_ignore_pathfinding': False, 'transfer_fare_ignore_pathenum': False, 'debug_output_columns': False, 'capacity': False, 'overlap_split_transit': False}
2017-05-09 15:23:27 [INFO/MainProcess] Reading configuration file Examples/test_scenario/demand_reg/config_ft.txt
2017-05-09 15:23:27 [INFO/MainProcess] Reading GTFS schedule
....blah blah blah transitfeed blahhh
2017-05-09 15:23:27 [WARNING/MainProcess] Adding shape_dist_traveled in miles
Traceback (most recent call last):
  File "//anaconda/envs/ft-tutorial-testing/bin/run_fasttrips", line 11, in <module>
    sys.exit(main())
  File "//anaconda/envs/ft-tutorial-testing/lib/python2.7/site-packages/fasttrips/Run.py", line 241, in main
    r = fasttrips.Run.run_fasttrips(**args_dict)
  File "//anaconda/envs/ft-tutorial-testing/lib/python2.7/site-packages/fasttrips/Run.py", line 186, in run_fasttrips
    ft.read_input_files()
  File "//anaconda/envs/ft-tutorial-testing/lib/python2.7/site-packages/fasttrips/FastTrips.py", line 150, in read_input_files
    self.stops, self.routes, Assignment.PREPEND_ROUTE_ID_TO_TRIP_ID)
  File "//anaconda/envs/ft-tutorial-testing/lib/python2.7/site-packages/fasttrips/Trip.py", line 396, in __init__
    self.add_shape_dist_traveled(stops)
  File "//anaconda/envs/ft-tutorial-testing/lib/python2.7/site-packages/fasttrips/Trip.py", line 584, in add_shape_dist_traveled
    (self.stop_times_df[Trip.STOPTIMES_COLUMN_STOP_SEQUENCE]==1), "calc shape_dist_traveled" ] = 0.0
  File "//anaconda/envs/ft-tutorial-testing/lib/python2.7/site-packages/pandas/core/ops.py", line 924, in wrapper
    return filler(self._constructor(na_op(self.values, other.values),
  File "//anaconda/envs/ft-tutorial-testing/lib/python2.7/site-packages/pandas/core/ops.py", line 894, in na_op
    result = lib.vec_binop(x, y, op)
  File "pandas/_libs/lib.pyx", line 894, in pandas._libs.lib.vec_binop (pandas/_libs/lib.c:15883)
  File "pandas/_libs/lib.pyx", line 887, in pandas._libs.lib.vec_binop (pandas/_libs/lib.c:15755)
TypeError: unsupported operand type(s) for &: 'float' and 'bool'
2017-05-09 15:23:27 [INFO/MainProcess] process shutting down
(//anaconda/envs/ft-tutorial-testing) bash-3.2$ 

```

**Comment by lmz** [comment]
NOT COOL :crying_cat_face:

**Comment by lmz** [comment]
ok, I think alpha 11 works :roll_eyes:

**Comment by e-lo** [comment]
```
2017-05-09 21:31:25 [INFO/MainProcess] Successfully completed!
2017-05-09 21:31:25 [INFO/MainProcess] process shutting down
```
